### ISSUE TITLE
build failed when i build for xiaomi a1 ,because of here is no extract_utils.sh

### ISSUE THREAD

**Issue by minotanoutman** [Cardinal-AOSP/vendor_cardinal#39]
py-64@py64-virtual-machine:/media/py-64/uu/cordinal_aosp/device/xiaomi/tissot$ ./extract-files.sh 
Unable to find helper script at ./../../xiaomi/msm8953-common/../../../vendor/lineage/build/tools/extract_utils.sh
py-64@py64-virtual-machine:/media/py-64/uu/cordinal_aosp/device/xiaomi/tissot$

**Comment by sathish2026** [comment]
You can't use extract script in cardinal .make suitable changes
